all: a

a: main.cc main_class.cc cpu.cc traits.h cpu.h main_class.h debug.cc debug.h system.h system.cc thread.cc thread.h
	g++ main.cc main_class.cc cpu.cc traits.h cpu.h main_class.h debug.cc debug.h system.h system.cc thread.cc thread.h -o a
